# Generated by Django 5.0.1 on 2024-01-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('candidate_display_config', models.TextField(help_text='JSON format of display configuration')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
            ],
            options={
                'indexes': [models.Index(fields=['department'], name='search_cand_departm_bc708d_idx'), models.Index(fields=['position'], name='search_cand_positio_6750cf_idx'), models.Index(fields=['location'], name='search_cand_locatio_9451ed_idx'), models.Index(fields=['status'], name='search_cand_status_1eb807_idx'), models.Index(fields=['company_name'], name='search_cand_company_de7a60_idx')],
            },
        ),
    ]
