# Generated by Django 5.0.1 on 2024-01-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_organization_name_organization_text_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['text_id'], name='search_orga_text_id_b1d087_idx'),
        ),
    ]
